# Generated by Django 2.2.4 on 2019-08-17 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_type', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('account_number', models.IntegerField()),
                ('available_balance', models.IntegerField()),
            ],
        ),
    ]
