# Generated by Django 2.2.4 on 2019-08-18 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField()),
                ('account', models.IntegerField()),
                ('description', models.CharField(max_length=60)),
                ('category', models.CharField(max_length=60)),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
