# Generated by Django 2.2.4 on 2019-08-18 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_transactions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transactions',
            new_name='Transaction',
        ),
    ]
