# Generated by Django 2.2.4 on 2019-08-18 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20190818_1722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='date',
            new_name='days_ago',
        ),
    ]
